on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy code
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 38.91.101.117
        username: farhanenterprise
        password: ktLY?$i&K8u&


# on: push
# name: ğŸš€ Deploy website on push
# jobs:
#   web-deploy:
#     name: ğŸ‰ Deploy Camp Reservation
#     runs-on: ubuntu-latest
#     steps:
#     - name: ğŸšš Get latest code
#       uses: actions/checkout@v2

#     - name: ğŸ“‚ Sync files
#       uses: SamKirkland/FTP-Deploy-Action@4.0.0
#       with:
#         server: 162.241.224.50
#         username: baramdatsol@reservations.campinspectors.com
#         password: ZjgBSRoSX]yL
